name: "Build SmartFace"
description: "Build SmartFace for all Frameworks & Applications"

inputs:
  public_url:
    description: "SmartFace PUBLIC_URL"
    required: true
  framework:
    description: "SmartFace Framework"
    required: true
  application:
    description: "SmartFace Application"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "yarn"

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

    - name: Build
      shell: bash
      run: yarn cross-env PUBLIC_URL=${{ inputs.public_url }}/${{ inputs.target-subpath }} node smart-face-scripts/index.js build ${{ inputs.framework }} ${{ inputs.application }}
