name: 'Deploy'
description: 'Deploy Buildfolder to AWS S3 Bucket'

inputs:
  target-root:
    description: 'Root path of the deployed target'
    required: true
  target-subpath:
    description: 'Subpath path of the deployed target'
    required: true
    default: 'error'
  aws-role-to-assume:
    description: 'AWS role to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials for Bucket
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Copy files to the Bucket with AWS CLI
      shell: bash
      run: aws s3 cp ./build/ s3://${{ inputs.target-root }}/${{ inputs.target-subpath }} --recursive --acl public-read
