name: 'Deploy to AWS bucket'
description: 'Generic action to deploy the file / folder to a specified AWS Bucket'

inputs:
  origin-path:
    description: File / Folder to upload
    required: true
  target-path:
    description: Target Path to upload to
    required: true
  aws-role-to-assume:
    required: true
  aws-region:
    required: true
  is-public:
    description: If sources in bucket should be public, set ACL Permission to public-read
    default: 'false'
  is-file:
    description: If origin-path is a file, skip the --recursive flag
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials for bucket
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Copy files to the bucket with AWS CLI
      shell: bash
      run: aws s3 cp ${{ inputs.origin-path }} s3://${{ inputs.target-path }}${{ inputs.is-file == 'false' && ' --recursive' || '' }}${{ inputs.is-public == 'true' && ' --acl public-read' || '' }}
