name: 'Send E-Mail Notification'
description: 'Send Notification to E-Mail Address via AWS'

inputs:
  aws-role-to-assume:
    description: 'AWS role to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  sender:
    description: 'Sender email'
    required: true
  recipient:
    description: 'Recipient email'
    required: true
  subject:
    description: 'Email subject'
    required: true
  html:
    description: 'Email body'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Send email
      shell: bash
      run: |
        aws ses send-email \
          --from "${{ inputs.sender }}" \
          --to "${{ inputs.recipient }}" \
          --subject "${{ inputs.subject }}" \
          --html "<p>${{ inputs.html }}</p>"
